// Elevaot actions
export const ELEVATORS_GET_SUCCESS = 'ELEVATORS_GET_SUCCESS';
export const ELEVATOR_REQUEST_SUCCESS = 'ELEVATOR_REQUEST_SUCCESS';
export const ELEVATOR_UPDATED = 'ELEVATOR_UPDATED';

// Occupant actions
export const OCCUPANT_GET_SUCCESS = 'OCCUPANT_GET_SUCCESS';
export const OCCUPANT_UPDATED = 'OCCUPANT_UPDATED';

// Building actions
export const BUILDING_GET_SUCCESS = 'BUILDING_GET_SUCCESS';