export const ELEVATORS_GET_SUCCESS = 'ELEVATORS_GET_SUCCESS';
export const ELEVATOR_REQUEST_SUCCESS = 'ELEVATOR_REQUEST_SUCCESS';
export const ELEVATOR_UPDATED = 'ELEVATOR_UPDATED';

export const OCCUPANT_GET_SUCCESS = 'OCCUPANT_GET_SUCCESS';

export const BUILDING_GET_SUCCESS = 'BUILDING_GET_SUCCESS';